# Generated by Django 5.1.4 on 2024-12-28 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Domain name without TLD', max_length=63, validators=[django.core.validators.RegexValidator(message='Domain name must contain only letters, numbers, and hyphens, and cannot start or end with a hyphen.', regex='^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='TLD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Top Level Domain (e.g. 'com', 'org', 'net')", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Domain name must contain only letters, numbers, and hyphens, and cannot start or end with a hyphen.', regex='^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Top Level Domain',
                'verbose_name_plural': 'Top Level Domains',
            },
        ),
        migrations.CreateModel(
            name='DomainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT')], default='A', max_length=5)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address for the record')),
                ('priority', models.IntegerField(default=0, help_text='Priority for MX records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='bind.domain')),
            ],
            options={
                'verbose_name': 'Domain Record',
                'verbose_name_plural': 'Domain Records',
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='bind.tld'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('name', 'tld')},
        ),
    ]
